name: firebase_todos_api
description: firebase api for todos
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cloud_firestore: ^4.0.5

  rxdart: ^0.27.6
  todos_api:
    path: ../todos_api
dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
