// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHt2lVmRJ-eSYTWAAEvbMOUDqdSo30SR0',
    appId: '1:716194157638:web:8fc8491c71bc314cf9a647',
    messagingSenderId: '716194157638',
    projectId: 'todo-ef12c',
    authDomain: 'todo-ef12c.firebaseapp.com',
    storageBucket: 'todo-ef12c.appspot.com',
    measurementId: 'G-YJYGDE7EE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRvN36F-N5_0M9zjuuSshTOLS-8UpH_QM',
    appId: '1:716194157638:android:51024fa79902bce8f9a647',
    messagingSenderId: '716194157638',
    projectId: 'todo-ef12c',
    storageBucket: 'todo-ef12c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3ezqlY89Gn1KzLcZSUrZTe1W9MAJwcQM',
    appId: '1:716194157638:ios:8c32e290e2ba7222f9a647',
    messagingSenderId: '716194157638',
    projectId: 'todo-ef12c',
    storageBucket: 'todo-ef12c.appspot.com',
    iosClientId: '716194157638-c3npmd33d7iitbnp990uuasnc36nq860.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
