name: firebase_auth_api
description: firebase implementation for authentication
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  auth_api:
    path: "../auth_api"
  firebase_auth: ^4.1.2
dev_dependencies:
  mocktail: ^0.3.0
  rxdart: ^0.27.6
  test: ^1.19.2
  very_good_analysis: ^3.1.0
